version: 2.1

orbs:
  gitleaks: upenn-libraries/gitleaks@0.1.1

workflows:
  check_for_secrets:
    jobs:
      - gitleaks/check_local:
          image: quay.io/upennlibraries/gitleaks:v1.24.0
          options: --redact --repo-config
